# Generated by Django 5.0.2 on 2024-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_classroom_attendance_lecture_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
