# Generated by Django 5.0.2 on 2024-02-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_classroom_name_alter_classroom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
